# Variables
@baseUrl = http://localhost:3333

# Health check
GET {{baseUrl}}/health

###

# @name getRooms
GET {{baseUrl}}/rooms

###

# @name createdRoom
POST {{baseUrl}}/rooms
Content-Type: application/json

{
  "name": "Sala de teste",
  "description": "descrição teste da sala teste"
}

###

@roomId = {{createdRoom.response.body.$.roomId}}

###

# @name getRoomQuestions
GET {{baseUrl}}/rooms/{{roomId}}/questions

